name: Deploy to Lambda
on:
  push:
    branches:
      - main

jobs:
  deploy_zip:
    name: Deploy authentication function
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build
        run: |
          npm install && npm run build && mkdir lambdas && mv node_modules dist/node_modules && cd dist && zip -r ../lambdas/generateToken.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: generateToken
          zip_file: lambdas/generateToken.zip
          memory_size: 128
          timeout: 10
          handler: index
          role: ${{secrets.IAM_ROLE}}
          runtime: nodejs16.x
